### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by barisione** [elements-x/elements-x#5]
* Go to https://elements-x.com/component/tabs
* Click the JS button
* End up on https://github.com/elements-x/elements-x/tree/master/src/lib/tabs which gives you a 404

The correct link doesn't have `src/` in the URL, that is it's https://github.com/elements-x/elements-x/tree/master/lib/tabs.

**Comment by allenhwkim** [comment]
Thanks for reporting these. This has been fixed and deployed.
